stages:
  - prepare
  - build
  - test
  - image

variables:
  GIT_DEPTH: 5
  GIT_SUBMODULE_STRATEGY: recursive

prepare swift packages:
  stage: prepare
  image: $CI_REGISTRY/disciplinas1/mc426/projeto/base:latest
  script:
    - swift package resolve
  cache:
    key: build-folder
    paths:
      - .build

build release:
  stage: build
  image: $CI_REGISTRY/disciplinas1/mc426/projeto/base:latest
  script:
    - swift build -c release
  cache:
    key: build-folder
    paths:
      - .build
  needs: ["prepare swift packages"]

build debug:
  stage: build
  image: $CI_REGISTRY/disciplinas1/mc426/projeto/base:latest
  script:
    - swift build -c debug
  cache:
    key: build-folder
    paths:
      - .build
  needs: ["prepare swift packages"]

.test config:
  stage: test
  image: $CI_REGISTRY/disciplinas1/mc426/projeto/base:latest
  parallel: 4
  script:
    - case $CI_NODE_INDEX in
    -   1) LOG_LEVEL=debug swift test -c $CONFIG --filter AppTests.CourseAPITests;;
    -   2) LOG_LEVEL=debug swift test -c $CONFIG --filter AppTests.DisciplineAPITests;;
    -   3) LOG_LEVEL=debug swift test -c $CONFIG --filter AppTests.SearchAPITests;;
    -   4) LOG_LEVEL=debug swift test -c $CONFIG --filter AppTests.ExtensionAPITests;;
    - esac
  cache:
    key: build-folder
    paths:
      - .build
    policy: pull

test release:
  extends: .test config
  variables:
    CONFIG: release
  needs: ["build release"]

test debug:
  extends: .test config
  variables:
    CONFIG: debug
  needs: ["build debug"]

build server image:
  stage: image
  image: docker:latest
  tags:
    - docker
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/disciplinas1/mc426/backend/base:latest . \
      --build-arg EXECUTABLE="$(swift build --package-path /build -c release --show-bin-path)/Run"
    - docker push $CI_REGISTRY/disciplinas1/mc426/backend/base:latest
  cache:
    key: build-folder
    paths:
      - .build
    policy: pull
  needs: ["build release"]
